package com.onlineexam.model;

public class Answer {
    private int answerId; // Generated by default as identity
    private int organisationId; // Not null
    private int subjectId; // Not null
    private int studentId;
    private int questionId;
    private int currentAttemp;
    public int getCurrentAttemp() {
		return currentAttemp;
	}

	public void setCurrentAttemp(int currentAttemp) {
		this.currentAttemp = currentAttemp;
	}


	private String givenAnswer; // Varchar2(100) NOT NULL

    // Constructors, getters, setters, and other methods omitted for brevity

    // Constructor
  

    // Getters and Setters
    public int getAnswerId() {
        return answerId;
    }

    public Answer(int organisationId, int subjectId, int studentId, int questionId, int currentAttemp,
			String givenAnswer) {
		super();
		this.organisationId = organisationId;
		this.subjectId = subjectId;
		this.studentId = studentId;
		this.questionId = questionId;
		this.currentAttemp = currentAttemp;
		this.givenAnswer = givenAnswer;
	}

	public void setAnswerId(int answerId) {
        this.answerId = answerId;
    }

    public int getOrganisationId() {
        return organisationId;
    }

    public void setOrganisationId(int organisationId) {
        this.organisationId = organisationId;
    }

    public int getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }

    public int getStudentId() {
        return studentId;
    }

    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    public int getQuestionId() {
        return questionId;
    }

    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }

    public String getGivenAnswer() {
        return givenAnswer;
    }

    public void setGivenAnswer(String givenAnswer) {
        this.givenAnswer = givenAnswer;
    }


    @Override
    public String toString() {
        return "Answer{" +
                "answerId=" + answerId +
                ", organisationId=" + organisationId +
                ", subjectId=" + subjectId +
                ", studentId=" + studentId +
                ", questionId=" + questionId +
                ", givenAnswer='" + givenAnswer + '\'' +
                
                '}';
    }
}

